version: '3'

services:
  web:
    container_name: todo-web
    image: node:16-alpine
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - BE_HOST=todo-server
      - BE_PORT=3001
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev

  server:
    container_name: todo-server
    image: node:16-alpine
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 3001:3001
    environment:
      - SQL_HOST=todo-sql
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_DATABASE=postgres
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev
  
  sql:
    container_name: todo-sql
    image: postgres:14-alpine
    user: postgres
    volumes:
      - ./sql/psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432