version: '3'

services:
  app1:
    container_name: app1
    image: alpine
    ports:
      - 8000:8000
    command:
      - sh
      - -c
      - |
        apk add python3 curl
        python3 -m http.server
  
  app2:
    container_name: app2
    image: alpine
    command:
      - sh
      - -c
      - |
        apk add curl
        curl http://app1:8000